### ISSUE TITLE
BiggerBazaar Lunar conversion not working in SP

### ISSUE THREAD

**Issue by piebaker** [MagnusMagnuson/RoR2Mods#5]
In SP the lunar to gold conversion doesn't seem to work. With the conversion rate set to 55 (or any number it seems) when exchanging lunar coins for gold the lunar coins get removed, but the gold is not deposited. Sharesuite is also enabled, but again, this is in SP only. MP works fine.

**Comment by MagnusMagnuson** [comment]
Hey, sorry for the late reply. I'm not getting any notifications for some reason. 

Anyway, thanks for reporting. This issue should have been fixed with the latest patch.
